// GENERATED by scripts/gen-adapter.mjs — review, then edit the TODOs by hand.
// Group membership pulled from ESPN's standings tree, because the teams feed
// carries no conference or division field.
import { withDefaults } from './schema.js'

export default withDefaults({
  id: 'epl',
  name: 'EPL',
  title: 'The EPL Schedule',
  season: 2026,
  espnPath: 'soccer/eng.1',

  // TODO review: these drive real behaviour, not just labels.
  standingsModel: 'winloss',   // winloss | winlosstie | points
  timeAxis: 'date',            // date | week   (NFL is week)
  postseason: 'none',          // series | single | none
  scoringFrequency: 'high',    // high | low
  approxGames: 20 * 0, // TODO: teams × games-per-team ÷ 2

  groupBy: 'conference',
  groups: {
    "2026-2027": "2026-2027"
  },
  groupByTeam: {
  ARS: '2026-2027',
  AVL: '2026-2027',
  BHA: '2026-2027',
  BOU: '2026-2027',
  BRE: '2026-2027',
  CHE: '2026-2027',
  COV: '2026-2027',
  CRY: '2026-2027',
  EVE: '2026-2027',
  FUL: '2026-2027',
  HUL: '2026-2027',
  IPS: '2026-2027',
  LEE: '2026-2027',
  LIV: '2026-2027',
  MAN: '2026-2027',
  MNC: '2026-2027',
  NEW: '2026-2027',
  NFO: '2026-2027',
  SUN: '2026-2027',
  TOT: '2026-2027',
  },
})
