// GENERATED by scripts/gen-adapter.mjs — review, then edit the TODOs by hand.
// Group membership pulled from ESPN's standings tree, because the teams feed
// carries no conference or division field.
import { withDefaults } from './schema.js'

export default withDefaults({
  id: 'nba',
  name: 'NBA',
  title: 'The NBA Schedule',
  season: 2026,
  espnPath: 'basketball/nba',

  // TODO review: these drive real behaviour, not just labels.
  standingsModel: 'winloss',   // winloss | winlosstie | points
  timeAxis: 'date',            // date | week   (NFL is week)
  postseason: 'none',          // series | single | none
  scoringFrequency: 'high',    // high | low
  approxGames: 30 * 0, // TODO: teams × games-per-team ÷ 2

  groupBy: 'conference',
  groups: {
    "East": "East",
    "West": "West"
  },
  groupByTeam: {
  ATL: 'East',
  BKN: 'East',
  BOS: 'East',
  CHA: 'East',
  CHI: 'East',
  CLE: 'East',
  DAL: 'West',
  DEN: 'West',
  DET: 'East',
  GS: 'West',
  HOU: 'West',
  IND: 'East',
  LAC: 'West',
  LAL: 'West',
  MEM: 'West',
  MIA: 'East',
  MIL: 'East',
  MIN: 'West',
  NO: 'West',
  NY: 'East',
  OKC: 'West',
  ORL: 'East',
  PHI: 'East',
  PHX: 'West',
  POR: 'West',
  SA: 'West',
  SAC: 'West',
  TOR: 'East',
  UTAH: 'West',
  WSH: 'East',
  },
})
