// GENERATED by scripts/gen-adapter.mjs — review, then edit the TODOs by hand.
// Group membership pulled from ESPN's standings tree, because the teams feed
// carries no conference or division field.
import { withDefaults } from './schema.js'

export default withDefaults({
  id: 'nfl',
  name: 'NFL',
  title: 'The NFL Schedule',
  season: 2026,
  espnPath: 'football/nfl',

  // TODO review: these drive real behaviour, not just labels.
  standingsModel: 'winloss',   // winloss | winlosstie | points
  timeAxis: 'date',            // date | week   (NFL is week)
  postseason: 'none',          // series | single | none
  scoringFrequency: 'high',    // high | low
  approxGames: 32 * 0, // TODO: teams × games-per-team ÷ 2

  groupBy: 'conference',
  groups: {
    "AFC": "AFC",
    "NFC": "NFC"
  },
  groupByTeam: {
  ARI: 'NFC',
  ATL: 'NFC',
  BAL: 'AFC',
  BUF: 'AFC',
  CAR: 'NFC',
  CHI: 'NFC',
  CIN: 'AFC',
  CLE: 'AFC',
  DAL: 'NFC',
  DEN: 'AFC',
  DET: 'NFC',
  GB: 'NFC',
  HOU: 'AFC',
  IND: 'AFC',
  JAX: 'AFC',
  KC: 'AFC',
  LAC: 'AFC',
  LAR: 'NFC',
  LV: 'AFC',
  MIA: 'AFC',
  MIN: 'NFC',
  NE: 'AFC',
  NO: 'NFC',
  NYG: 'NFC',
  NYJ: 'AFC',
  PHI: 'NFC',
  PIT: 'AFC',
  SEA: 'NFC',
  SF: 'NFC',
  TB: 'NFC',
  TEN: 'AFC',
  WSH: 'NFC',
  },
})
