#!/usr/bin/env node
// Scaffolds a league adapter with REAL data pulled from ESPN, rather than a
// hand-typed team list.
//
// This exists because of a mistake worth not repeating: ESPN's teams feed carries
// no conference or division field for ANY league (verified for NBA, NFL, WNBA).
// That mapping has to be declared by hand — and hand-typed team lists are exactly
// the kind of thing that is silently wrong for one team all season. Pulling it from
// the standings endpoint makes it correct by construction.
//
//   node scripts/gen-adapter.mjs --league nba --path basketball/nba --season 2027
//
// Node built-ins only.

import { writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SITE = 'https://site.api.espn.com/apis/site/v2/sports'
const CORE = 'https://site.api.espn.com/apis/v2/sports'

const arg = (k, d) => {
  const i = process.argv.indexOf(`--${k}`)
  return i > -1 ? process.argv[i + 1] : d
}

const league = arg('league')
const espnPath = arg('path')
const season = Number(arg('season')) || new Date().getFullYear()

if (!league || !espnPath) {
  console.error('usage: gen-adapter.mjs --league nba --path basketball/nba [--season 2027]')
  process.exit(1)
}

const getJson = async (url) => {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`)
  return res.json()
}

// Groups live only in the standings tree, keyed by conference/division nodes.
function collectGroups(node, path = []) {
  const out = []
  const label = node.abbreviation || node.name
  const next = label && path.length === 0 && !node.standings ? path : [...path, label].filter(Boolean)
  if (node.standings?.entries?.length) {
    out.push({ key: label, teams: node.standings.entries.map((e) => e.team.abbreviation) })
  }
  for (const child of node.children || []) out.push(...collectGroups(child, next))
  return out
}

const teamsDoc = await getJson(`${SITE}/${espnPath}/teams`)
const teams = teamsDoc.sports[0].leagues[0].teams.map(({ team: t }) => ({
  abbr: t.abbreviation,
  name: t.displayName,
}))

let groups = []
try {
  groups = collectGroups(await getJson(`${CORE}/${espnPath}/standings?season=${season}`))
} catch {
  console.warn('  (standings unavailable — groupByTeam left empty, fill it in by hand)')
}

const groupByTeam = {}
for (const g of groups) for (const abbr of g.teams) groupByTeam[abbr] = g.key

const missing = teams.filter((t) => !groupByTeam[t.abbr])
const lines = Object.entries(groupByTeam)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([abbr, g]) => `  ${abbr}: '${g}',`)

const file = `// GENERATED by scripts/gen-adapter.mjs — review, then edit the TODOs by hand.
// Group membership pulled from ESPN's standings tree, because the teams feed
// carries no conference or division field.
import { withDefaults } from './schema.js'

export default withDefaults({
  id: '${league}',
  name: '${league.toUpperCase()}',
  title: 'The ${league.toUpperCase()} Schedule',
  season: ${season},
  espnPath: '${espnPath}',

  // TODO review: these drive real behaviour, not just labels.
  standingsModel: 'winloss',   // winloss | winlosstie | points
  timeAxis: 'date',            // date | week   (NFL is week)
  postseason: 'none',          // series | single | none
  scoringFrequency: 'high',    // high | low
  approxGames: ${teams.length} * 0, // TODO: teams × games-per-team ÷ 2

  groupBy: '${groups.length ? 'conference' : 'none'}',
  groups: ${JSON.stringify(Object.fromEntries(groups.map((g) => [g.key, g.key])), null, 2).replace(/\n/g, '\n  ')},
  groupByTeam: {
${lines.join('\n')}
  },
})
`

await mkdir(join(ROOT, 'adapters'), { recursive: true })
const out = join(ROOT, 'adapters', `${league}.js`)
await writeFile(out, file)

console.log(`${teams.length} teams · ${groups.length} groups → adapters/${league}.js`)
for (const g of groups) console.log(`  ${g.key}: ${g.teams.length}`)
if (missing.length) console.warn(`  ⚠ ungrouped: ${missing.map((t) => t.abbr).join(', ')}`)
